import sys
import os
from unittest.mock import patch, MagicMock

# Ensure the root directory is in the path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), ".")))

from src.monitor import fetch_transcript
from src.orchestrator import process_short_approval

def test_fallback_phase1_fail_phase2_success():
    video_id = "test_video_fallback_success"
    
    print(f"\n--- Testing Fallback: Phase 1 Fail, Phase 2 Success ---")
    
    # Mocking YouTubeTranscriptApi.fetch to fail (Phase 1)
    # We patch it where it is used: src.monitor
    with patch("src.monitor.YouTubeTranscriptApi") as mock_api_class:
        mock_api_instance = mock_api_class.return_value
        mock_api_instance.fetch.side_effect = Exception("Phase 1: YouTube Transcript API Failed")
        
        # Mocking Phase 2 components
        with patch("src.monitor.download_audio") as mock_download, \
             patch("src.monitor.transcribe_audio_deepgram") as mock_deepgram, \
             patch("os.path.exists") as mock_exists, \
             patch("os.remove") as mock_remove:
            
            mock_download.return_value = "/tmp/fake_audio.m4a"
            mock_exists.return_value = True
            mock_deepgram.return_value = "This is a transcript generated by Deepgram (Phase 2)."
            
            transcript = fetch_transcript(video_id)
            
            print(f"Resulting transcript: {transcript}")
            
            # Assertions
            assert transcript == "This is a transcript generated by Deepgram (Phase 2)."
            mock_api_instance.fetch.assert_called_once_with(video_id)
            mock_download.assert_called_once()
            mock_deepgram.assert_called_once_with("/tmp/fake_audio.m4a")
            mock_remove.assert_called_once_with("/tmp/fake_audio.m4a")
            
            print("✅ Phase 1 Fail -> Phase 2 Success: PASSED")

def test_fallback_both_fail():
    video_id = "test_video_both_fail"
    
    print(f"\n--- Testing Fallback: Both Phases Fail ---")
    
    with patch("src.monitor.YouTubeTranscriptApi") as mock_api_class:
        mock_api_instance = mock_api_class.return_value
        mock_api_instance.fetch.side_effect = Exception("Phase 1 Failed")
        
        with patch("src.monitor.download_audio") as mock_download, \
             patch("os.path.exists") as mock_exists, \
             patch("os.remove") as mock_remove:
            
            mock_download.return_value = "/tmp/fake_audio_fail.m4a"
            mock_exists.return_value = True
            
            with patch("src.monitor.transcribe_audio_deepgram") as mock_deepgram:
                mock_deepgram.return_value = None # Phase 2 fails
                
                transcript = fetch_transcript(video_id)
                
                print(f"Resulting transcript: {transcript}")
                
                # Assertions
                assert transcript is None
                mock_api_instance.fetch.assert_called_once_with(video_id)
                mock_download.assert_called_once()
                mock_deepgram.assert_called_once_with("/tmp/fake_audio_fail.m4a")
                mock_remove.assert_called_once_with("/tmp/fake_audio_fail.m4a")
                
                print("✅ Both Phases Fail: PASSED")

def test_orchestrator_notification():
    video_id = "notify_video_789"
    title = "Failing Video Title"
    
    print(f"\n--- Testing Orchestrator Notification on Failure ---")
    
    with patch("src.orchestrator.fetch_transcript") as mock_fetch:
        mock_fetch.return_value = None # Both phases failed
        
        with patch("src.telegram_bot.send_message") as mock_send:
            process_short_approval(video_id, title)
            
            # Verify the ❌ message was sent
            expected_msg = f"❌ No transcript found for video: {title} ({video_id}). Production halted."
            mock_send.assert_called_once_with(expected_msg)
            
            print(f"Notification sent: {expected_msg}")
            print("✅ Orchestrator Notification: PASSED")

if __name__ == "__main__":
    try:
        test_fallback_phase1_fail_phase2_success()
        test_fallback_both_fail()
        test_orchestrator_notification()
        print("\n✨ All reproduction tests passed successfully! ✨")
    except AssertionError as e:
        print(f"\n❌ Test Failed: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"\n💥 An unexpected error occurred: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
